import type { Category, Tool, Article } from "@/lib/types";
import {
  PenTool,
  Paintbrush,
  Globe,
  Megaphone,
  CodeXml,
  Sun,
} from "lucide-react";

export const categories: Category[] = [
  {
    id: "writing",
    name: "AI Writing",
    icon: PenTool,
    imageId: "category-writing",
  },
  {
    id: "design",
    name: "AI Design",
    icon: Paintbrush,
    imageId: "category-design",
  },
  {
    id: "web",
    name: "Web Build",
    icon: Globe,
    imageId: "category-web",
  },
  {
    id: "marketing",
    name: "Marketing",
    icon: Megaphone,
    imageId: "category-marketing",
  },
  {
    id: "dev",
    name: "Developer",
    icon: CodeXml,
    imageId: "category-dev",
  },
  {
    id: "daily",
    name: "Daily Use",
    icon: Sun,
    imageId: "category-daily",
  },
];

export const tools: Tool[] = [
  {
    id: "chatgpt",
    name: "ChatGPT",
    description: "AI tool for writing, summarizing, and generating content.",
    link: "https://chat.openai.com/",
    category: "writing",
    imageId: "tool-chatgpt",
  },
  {
    id: "dall-e-3",
    name: "DALL·E 3",
    description: "AI tool for generating images from text prompts.",
    link: "https://openai.com/dall-e-3",
    category: "design",
    imageId: "tool-dalle",
  },
  {
    id: "midjourney",
    name: "Midjourney",
    description: "Generate high-quality images from textual descriptions.",
    link: "https://www.midjourney.com/",
    category: "design",
    imageId: "tool-midjourney",
  },
  {
    id: "github-copilot",
    name: "GitHub Copilot",
    description: "Your AI pair programmer that suggests code in real-time.",
    link: "https://github.com/features/copilot",
    category: "dev",
    imageId: "tool-github-copilot",
  },
  {
    id: "notion-ai",
    name: "Notion AI",
    description: "Integrate AI power into your notes and docs.",
    link: "https://www.notion.so/product/ai",
    category: "daily",
    imageId: "tool-notion-ai",
  },
  {
    id: "canva",
    name: "Canva Magic Studio",
    description: "All the power of AI, all in one place. Create compelling content, fast.",
    link: "https://www.canva.com/magic-studio/",
    category: "design",
    imageId: "tool-canva",
  },
  {
    id: "grammarly",
    name: "Grammarly",
    description: "AI-powered writing assistant for mistake-free writing.",
    link: "https://www.grammarly.com/",
    category: "writing",
    imageId: "tool-grammarly",
  },
  {
    id: "synthesia",
    name: "Synthesia",
    description: "Create professional AI videos from text in minutes.",
    link: "https://www.synthesia.io/",
    category: "marketing",
    imageId: "tool-synthesia",
  },
  {
    id: "10web",
    name: "10Web",
    description: "AI website builder to create a professional website in minutes.",
    link: "https://10web.io/",
    category: "web",
    imageId: "tool-10web",
    isSponsored: true,
  },
  {
    id: "jasper",
    name: "Jasper",
    description: "AI Content Platform for businesses to create content.",
    link: "https://www.jasper.ai/",
    category: "writing",
    imageId: "tool-jasper",
    isSponsored: true,
  },
  {
    id: "copy-ai",
    name: "Copy.ai",
    description: "Generate marketing copy and content with AI.",
    link: "https://www.copy.ai/",
    category: "marketing",
    imageId: "tool-copy-ai",
  },
  {
    id: "rytr",
    name: "Rytr",
    description: "An AI writing assistant that helps you create content.",
    link: "https://rytr.me/",
    category: "writing",
    imageId: "tool-rytr",
  },
  {
    id: "frase",
    name: "Frase",
    description: "AI tool for content research, writing, and optimization.",
    link: "https://www.frase.io/",
    category: "writing",
    imageId: "tool-frase",
  },
  {
    id: "surfer-seo",
    name: "Surfer SEO",
    description: "SEO tool that helps you write content that ranks.",
    link: "https://surferseo.com/",
    category: "marketing",
    imageId: "tool-surfer-seo",
  },
  {
    id: "semrush",
    name: "Semrush",
    description: "All-in-one marketing toolkit for digital marketing professionals.",
    link: "https://www.semrush.com/",
    category: "marketing",
    imageId: "tool-semrush",
  },
  {
    id: "ahrefs",
    name: "Ahrefs",
    description: "SEO tools & resources to grow your search traffic.",
    link: "https://ahrefs.com/",
    category: "marketing",
    imageId: "tool-ahrefs",
  },
  {
    id: "moz",
    name: "Moz",
    description: "SEO software and data to help you increase traffic and visibility.",
    link: "https://moz.com/",
    category: "marketing",
    imageId: "tool-moz",
  },
  {
    id: "hubspot",
    name: "HubSpot",
    description: "Platform of marketing, sales, customer service, and CRM software.",
    link: "https://www.hubspot.com/",
    category: "marketing",
    imageId: "tool-hubspot",
  },
  {
    id: "mailchimp",
    name: "Mailchimp",
    description: "Email marketing and automation platform.",
    link: "https://mailchimp.com/",
    category: "marketing",
    imageId: "tool-mailchimp",
  },
  {
    id: "buffer",
    name: "Buffer",
    description: "Social media management platform.",
    link: "https://buffer.com/",
    category: "marketing",
    imageId: "tool-buffer",
  },
  {
    id: "hootsuite",
    name: "Hootsuite",
    description: "Manage all your social media in one place.",
    link: "https://www.hootsuite.com/",
    category: "marketing",
    imageId: "tool-hootsuite",
  },
  {
    id: "framer",
    name: "Framer",
    description: "A tool to design and build websites with AI.",
    link: "https://www.framer.com/",
    category: "web",
    imageId: "tool-framer",
  },
  {
    id: "webflow",
    name: "Webflow",
    description: "Build responsive websites visually.",
    link: "https://webflow.com/",
    category: "web",
    imageId: "tool-webflow",
  },
  {
    id: "wix",
    name: "Wix",
    description: "Create a professional website with the Wix website builder.",
    link: "https://www.wix.com/",
    category: "web",
    imageId: "tool-wix",
  },
  {
    id: "squarespace",
    name: "Squarespace",
    description: "Website builder for portfolios, blogs, and online stores.",
    link: "https://www.squarespace.com/",
    category: "web",
    imageId: "tool-squarespace",
  },
  {
    id: "shopify",
    name: "Shopify",
    description: "E-commerce platform for online stores and retail point-of-sale systems.",
    link: "https://www.shopify.com/",
    category: "web",
    imageId: "tool-shopify",
  },
  {
    id: "bigcommerce",
    name: "BigCommerce",
    description: "E-commerce platform for growing businesses.",
    link: "https://www.bigcommerce.com/",
    category: "web",
    imageId: "tool-bigcommerce",
  },
  {
    id: "magento",
    name: "Magento",
    description: "Open-source e-commerce platform.",
    link: "https://magento.com/",
    category: "web",
    imageId: "tool-magento",
  },
  {
    id: "woocommerce",
    name: "WooCommerce",
    description: "Open-source e-commerce plugin for WordPress.",
    link: "https://woocommerce.com/",
    category: "web",
    imageId: "tool-woocommerce",
  },
  {
    id: "elementor",
    name: "Elementor",
    description: "WordPress website builder plugin.",
    link: "https://elementor.com/",
    category: "web",
    imageId: "tool-elementor",
  },
  {
    id: "divi",
    name: "Divi",
    description: "WordPress theme and visual page builder.",
    link: "https://www.elegantthemes.com/gallery/divi/",
    category: "web",
    imageId: "tool-divi",
  },
  {
    id: "figma",
    name: "Figma",
    description: "Collaborative interface design tool.",
    link: "https://www.figma.com/",
    category: "design",
    imageId: "tool-figma",
  },
  {
    id: "sketch",
    name: "Sketch",
    description: "Digital design toolkit for macOS.",
    link: "https://www.sketch.com/",
    category: "design",
    imageId: "tool-sketch",
  },
  {
    id: "adobe-xd",
    name: "Adobe XD",
    description: "Vector-based UX design tool for web and mobile apps.",
    link: "https://www.adobe.com/products/xd.html",
    category: "design",
    imageId: "tool-adobe-xd",
  },
  {
    id: "invision",
    name: "InVision",
    description: "Digital product design and development platform.",
    link: "https://www.invisionapp.com/",
    category: "design",
    imageId: "tool-invision",
  },
  {
    id: "marvel",
    name: "Marvel",
    description: "Design and prototyping tool for designers.",
    link: "https://marvelapp.com/",
    category: "design",
    imageId: "tool-marvel",
  },
  {
    id: "zeplin",
    name: "Zeplin",
    description: "Handoff tool for designers and developers.",
    link: "https://zeplin.io/",
    category: "design",
    imageId: "tool-zeplin",
  },
  {
    id: "abstract",
    name: "Abstract",
    description: "Version control for design files.",
    link: "https://www.abstract.com/",
    category: "design",
    imageId: "tool-abstract",
  },
  {
    id: "loom",
    name: "Loom",
    description: "Video messaging for work.",
    link: "https://www.loom.com/",
    category: "daily",
    imageId: "tool-loom",
  },
  {
    id: "slack",
    name: "Slack",
    description: "Collaboration hub for work.",
    link: "https://slack.com/",
    category: "daily",
    imageId: "tool-slack",
  },
  {
    id: "trello",
    name: "Trello",
    description: "Web-based Kanban-style list-making application.",
    link: "https://trello.com/",
    category: "daily",
    imageId: "tool-trello",
  },
  {
    id: "asana",
    name: "Asana",
    description: "Work management platform teams use to stay focused.",
    link: "https://asana.com/",
    category: "daily",
    imageId: "tool-asana",
  },
  {
    id: "jira",
    name: "Jira",
    description: "Agile project management tool for software teams.",
    link: "https://www.atlassian.com/software/jira",
    category: "dev",
    imageId: "tool-jira",
  },
  {
    id: "confluence",
    name: "Confluence",
    description: "Content collaboration tool for teams.",
    link: "https://www.atlassian.com/software/confluence",
    category: "daily",
    imageId: "tool-confluence",
  },
  {
    id: "miro",
    name: "Miro",
    description: "Online collaborative whiteboard platform.",
    link: "https://miro.com/",
    category: "daily",
    imageId: "tool-miro",
  },
  {
    id: "mural",
    name: "Mural",
    description: "Digital workspace for visual collaboration.",
    link: "https://www.mural.co/",
    category: "daily",
    imageId: "tool-mural",
  },
  {
    id: "airtable",
    name: "Airtable",
    description: "Spreadsheet-database hybrid, with the features of a database but applied to a spreadsheet.",
    link: "https://www.airtable.com/",
    category: "daily",
    imageId: "tool-airtable",
  },
  {
    id: "zapier",
    name: "Zapier",
    description: "Automate workflows by connecting your apps and services.",
    link: "https://zapier.com/",
    category: "daily",
    imageId: "tool-zapier",
  },
  {
    id: "integromat",
    name: "Integromat",
    description: "Automation platform for connecting apps and APIs.",
    link: "https://www.make.com/en/integromat",
    category: "daily",
    imageId: "tool-integromat",
  },
  {
    id: "ifttt",
    name: "IFTTT",
    description: "If This Then That, a free way to get your apps and devices working together.",
    link: "https://ifttt.com/",
    category: "daily",
    imageId: "tool-ifttt",
  },
  {
    id: "descript",
    name: "Descript",
    description: "AI-powered audio and video editing.",
    link: "https://www.descript.com/",
    category: "writing",
    imageId: "tool-descript",
  },
  {
    id: "otter-ai",
    name: "Otter.ai",
    description: "AI-powered transcription service.",
    link: "https://otter.ai/",
    category: "writing",
    imageId: "tool-otter-ai",
  },
  {
    id: "fireflies-ai",
    name: "Fireflies.ai",
    description: "AI assistant for your meetings.",
    link: "https://fireflies.ai/",
    category: "daily",
    imageId: "tool-fireflies-ai",
  },
  {
    id: "elevenlabs",
    name: "ElevenLabs",
    description: "AI-powered text-to-speech and voice cloning.",
    link: "https://elevenlabs.io/",
    category: "writing",
    imageId: "tool-elevenlabs",
  },
  {
    id: "heygen",
    name: "HeyGen",
    description: "AI video generation platform.",
    link: "https://www.heygen.com/",
    category: "marketing",
    imageId: "tool-heygen",
  },
  {
    id: "runway",
    name: "Runway",
    description: "AI video editing and generation tools.",
    link: "https://runwayml.com/",
    category: "design",
    imageId: "tool-runway",
  },
  {
    id: "pika",
    name: "Pika",
    description: "Idea to video platform.",
    link: "https://pika.art/",
    category: "design",
    imageId: "tool-pika",
  },
  {
    id: "luma-ai",
    name: "Luma AI",
    description: "Generate 3D models from text or images.",
    link: "https://lumalabs.ai/",
    category: "design",
    imageId: "tool-luma-ai",
  },
  {
    id: "spline",
    name: "Spline",
    description: "3D design tool for the web.",
    link: "https://spline.design/",
    category: "design",
    imageId: "tool-spline",
  },
  {
    id: "beautiful-ai",
    name: "Beautiful.ai",
    description: "AI-powered presentation maker.",
    link: "https://www.beautiful.ai/",
    category: "design",
    imageId: "tool-beautiful-ai",
  },
  {
    id: "tome",
    name: "Tome",
    description: "AI-powered storytelling format.",
    link: "https://tome.app/",
    category: "design",
    imageId: "tool-tome",
  },
  {
    id: "gamma",
    name: "Gamma",
    description: "A new medium for presenting ideas, powered by AI.",
    link: "https://gamma.app/",
    category: "design",
    imageId: "tool-gamma",
  },
  {
    id: "claude",
    name: "Claude",
    description: "A next-generation AI assistant by Anthropic.",
    link: "https://claude.ai/",
    category: "writing",
    imageId: "tool-claude",
  },
  {
    id: "perplexity-ai",
    name: "Perplexity AI",
    description: "An AI search engine and chatbot.",
    link: "https://www.perplexity.ai/",
    category: "daily",
    imageId: "tool-perplexity-ai",
  },
  {
    id: "poe",
    name: "Poe",
    description: "Fast, helpful AI chat.",
    link: "https://poe.com/",
    category: "daily",
    imageId: "tool-poe",
  },
  {
    id: "bard",
    name: "Google Gemini (Bard)",
    description: "Your creative and helpful collaborator, by Google.",
    link: "https://gemini.google.com/",
    category: "writing",
    imageId: "tool-bard",
  },
  {
    id: "copilot",
    name: "Microsoft Copilot",
    description: "Your everyday AI companion from Microsoft.",
    link: "https://copilot.microsoft.com/",
    category: "daily",
    imageId: "tool-copilot",
  },
  {
    id: "v0-dev",
    name: "v0.dev",
    description: "Generate UI with simple text prompts.",
    link: "https://v0.dev/",
    category: "dev",
    imageId: "tool-v0-dev",
  },
  {
    id: "cursor",
    name: "Cursor",
    description: "The AI-first code editor.",
    link: "https://cursor.sh/",
    category: "dev",
    imageId: "tool-cursor",
  },
  {
    id: "replit",
    name: "Replit",
    description: "An online IDE, compiler, and interpreter with AI features.",
    link: "https://replit.com/",
    category: "dev",
    imageId: "tool-replit",
  },
  {
    id: "codesandbox",
    name: "CodeSandbox",
    description: "An online code editor and prototyping tool.",
    link: "https://codesandbox.io/",
    category: "dev",
    imageId: "tool-codesandbox",
  },
  {
    id: "vercel",
    name: "Vercel",
    description: "Platform for frontend developers to build and deploy web applications.",
    link: "https://vercel.com/",
    category: "dev",
    imageId: "tool-vercel",
  },
  {
    id: "netlify",
    name: "Netlify",
    description: "Platform for modern web development.",
    link: "https://www.netlify.com/",
    category: "dev",
    imageId: "tool-netlify",
  },
  {
    id: "firebase",
    name: "Firebase",
    description: "Google's platform for building and running successful apps.",
    link: "https://firebase.google.com/",
    category: "dev",
    imageId: "tool-firebase",
  },
  {
    id: "supabase",
    name: "Supabase",
    description: "The open source Firebase alternative.",
    link: "https://supabase.com/",
    category: "dev",
    imageId: "tool-supabase",
  },
  {
    id: "appwrite",
    name: "Appwrite",
    description: "Open-source backend platform for web, mobile, and flutter developers.",
    link: "https://appwrite.io/",
    category: "dev",
    imageId: "tool-appwrite",
  },
  {
    id: "docker",
    name: "Docker",
    description: "Platform for developing, shipping, and running applications in containers.",
    link: "https://www.docker.com/",
    category: "dev",
    imageId: "tool-docker",
  },
  {
    id: "kubernetes",
    name: "Kubernetes",
    description: "Open-source system for automating deployment, scaling, and management of containerized applications.",
    link: "https://kubernetes.io/",
    category: "dev",
    imageId: "tool-kubernetes",
  },
  {
    id: "terraform",
    name: "Terraform",
    description: "Infrastructure as code software tool.",
    link: "https://www.terraform.io/",
    category: "dev",
    imageId: "tool-terraform",
  },
  {
    id: "ansible",
    name: "Ansible",
    description: "Open-source software provisioning, configuration management, and application-deployment tool.",
    link: "https://www.ansible.com/",
    category: "dev",
    imageId: "tool-ansible",
  },
  {
    id: "jenkins",
    name: "Jenkins",
    description: "Open-source automation server.",
    link: "https://www.jenkins.io/",
    category: "dev",
    imageId: "tool-jenkins",
  },
  {
    id: "gitlab",
    name: "GitLab",
    description: "A complete DevOps platform.",
    link: "https://about.gitlab.com/",
    category: "dev",
    imageId: "tool-gitlab",
  },
  {
    id: "bitbucket",
    name: "Bitbucket",
    description: "Git repository management solution.",
    link: "https://bitbucket.org/",
    category: "dev",
    imageId: "tool-bitbucket",
  },
  {
    id: "postman",
    name: "Postman",
    description: "API platform for building and using APIs.",
    link: "https://www.postman.com/",
    category: "dev",
    imageId: "tool-postman",
  },
  {
    id: "insomnia",
    name: "Insomnia",
    description: "The open-source API client.",
    link: "https://insomnia.rest/",
    category: "dev",
    imageId: "tool-insomnia",
  },
  {
    id: "sentry",
    name: "Sentry",
    description: "Error tracking and performance monitoring.",
    link: "https://sentry.io/",
    category: "dev",
    imageId: "tool-sentry",
  },
  {
    id: "datadog",
    name: "Datadog",
    description: "Monitoring and security platform for cloud applications.",
    link: "https://www.datadoghq.com/",
    category: "dev",
    imageId: "tool-datadog",
  },
  {
    id: "new-relic",
    name: "New Relic",
    description: "Observability platform for engineers.",
    link: "https://newrelic.com/",
    category: "dev",
    imageId: "tool-new-relic",
  },
  {
    id: "launchdarkly",
    name: "LaunchDarkly",
    description: "Feature management platform.",
    link: "https://launchdarkly.com/",
    category: "dev",
    imageId: "tool-launchdarkly",
  },
  {
    id: "optimizely",
    name: "Optimizely",
    description: "Digital experience platform.",
    link: "https://www.optimizely.com/",
    category: "marketing",
    imageId: "tool-optimizely",
  },
  {
    id: "google-analytics",
    name: "Google Analytics",
    description: "Web analytics service that tracks and reports website traffic.",
    link: "https://analytics.google.com/",
    category: "marketing",
    imageId: "tool-google-analytics",
  },
  {
    id: "mixpanel",
    name: "Mixpanel",
    description: "Product analytics for mobile, web, and other digital products.",
    link: "https://mixpanel.com/",
    category: "marketing",
    imageId: "tool-mixpanel",
  },
  {
    id: "amplitude",
    name: "Amplitude",
    description: "Product intelligence platform.",
    link: "https://amplitude.com/",
    category: "marketing",
    imageId: "tool-amplitude",
  },
  {
    id: "segment",
    name: "Segment",
    description: "Customer data platform (CDP).",
    link: "https://segment.com/",
    category: "marketing",
    imageId: "tool-segment",
  },
  {
    id: "stripe",
    name: "Stripe",
    description: "Online payment processing for internet businesses.",
    link: "https://stripe.com/",
    category: "web",
    imageId: "tool-stripe",
  },
  {
    id: "paypal",
    name: "PayPal",
    description: "Online payments system.",
    link: "https://www.paypal.com/",
    category: "web",
    imageId: "tool-paypal",
  },
  {
    id: "algolia",
    name: "Algolia",
    description: "Hosted search API that provides fast, relevant search.",
    link: "https://www.algolia.com/",
    category: "dev",
    imageId: "tool-algolia",
  },
  {
    id: "twilio",
    name: "Twilio",
    description: "Cloud communications platform as a service.",
    link: "https://www.twilio.com/",
    category: "dev",
    imageId: "tool-twilio",
  },
];

export const articles: Article[] = [
  {
    id: "top-30-ai-tools",
    title: "Top 30 AI Tools in 2025",
    description:
      "Explore trending AI tools revolutionizing creativity and productivity across various industries.",
    link: "#",
    imageId: "article-1",
  },
  {
    id: "ai-in-marketing",
    title: "How AI is Reshaping the Marketing Landscape",
    description:
      "Discover how artificial intelligence is personalizing customer experiences and automating campaigns.",
    link: "#",
    imageId: "article-2",
  },
  {
    id: "future-of-web-dev",
    title: "The Future of Web Development is AI-Powered",
    description:
      "A deep dive into AI-driven platforms and tools that are accelerating the web creation process.",
    link: "#",
    imageId: "article-3",
  },
];
